music_directory     "/mnt/HunggParado/Music Ipod Lostless"
db_file             "/home/arkparado/.local/share/mpd/database"
log_file            "/home/arkparado/.local/share/mpd/log"
pid_file            "/home/arkparado/.local/share/mpd/pid"
state_file          "/home/arkparado/.local/share/mpd/state"
sticker_file        "/home/arkparado/.local/share/mpd/sticker.sql"

bind_to_address     "127.0.0.1"
port                "6600"

audio_output {
    type    "pipewire"
    name    "PipeWire Output"
}
